### ISSUE TITLE
Potentially a virus

### ISSUE THREAD

**Issue by ItsYaBoyBanana** [b1scoito/clicker#28]
39/70 antivirus has flagged this as a virus (https://www.virustotal.com). Also when this file is executed, it sends information to this IP 104.72.157.41:443

![image](https://user-images.githubusercontent.com/61800921/118851822-73c70d80-b8d2-11eb-99e2-5369d061ef78.png)

**Comment by b1scoito** [comment]
Please refer to the previous made issue #27

Compile it yourself and x64 (64-bit) and try to run VirusTotal, results will be way different.
The reason for this amount of flags are mainly because of the low-level mouse and keyboard hooking and input stuff.

The current release is compiled in x86 (32-bit). That's why so many flags.

Now about the IP Traffic, their VM got an IP unrelated to my application, my application does not communicate in any way with the internet, it doesn't even have the libraries for that. This IP is related to Windows's or other application's telemetry.

**Comment by Landonator08** [comment]
My computer flagged a trojan after i ran all day, Then i got a message that said logged in from another location smh

**Comment by b1scoito** [comment]
Wasn't because of this project.
