### ISSUE TITLE
poger stuff

### ISSUE THREAD

**Issue by DoingCrackAtTheDvdStore** [b1scoito/clicker#42]
much thanks, please go kys 
- yours truly
![image](https://user-images.githubusercontent.com/93857145/168094969-d5a32aec-a3d5-4530-8a7c-5e13236bc315.png)

**Comment by WalEl6512** [comment]
huhuhuhuhhhuuhu

**Comment by DoingCrackAtTheDvdStore** [comment]
windows defender said ight so we gucci

**Comment by b1scoito** [comment]
Please refer to these previously made issues: #28 #27 #33 #39

Has been said multiple times already. The application is not a virus, those are false flags, my code is open-source, you can compile it yourself. The reason for theses false flags is because my application behaves like a malware by setting keyboard/mouse hooks (often used for key-logging purposes), but here I use to see when the mouse is pressed down and when a keyboard key is pressed down (for the inventory detection).

**Comment by DoingCrackAtTheDvdStore** [comment]
sussy
